language: r
warnings_are_errors: true
cache: 
  packages: true

repos:
  CRAN: https://cloud.r-project.org

notifications:
  email:
    on_success: change
    on_failure: change

service_name: travis-pro
repo_token: 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


after_success:
  - Rscript -e 'covr::codecov()'
