language: r
warnings_are_errors: true
cache: 
  packages: true

repos:
  CRAN: https://cloud.r-project.org

notifications:
  email:
    on_success: change
    on_failure: change

service_name: travis-pro
repo_token: mYAwUYufK46TBtlMOSzFxN2RB96dK7nOM


after_success:
  - Rscript -e 'covr::codecov()'
