// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// disaggregate_mdCPP
List disaggregate_mdCPP(const List macro_data);
RcppExport SEXP synthACS_disaggregate_mdCPP(SEXP macro_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type macro_data(macro_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(disaggregate_mdCPP(macro_data));
    return rcpp_result_gen;
END_RCPP
}
